### ISSUE TITLE
What about Test purchases?

### ISSUE THREAD

**Issue by iNuman** [akshaaatt/Google-IAP#28]
I didn't find anything related to testing purchases why is it directly charges from me instead of test purchases.

**Comment by akshaaatt** [comment]
https://developer.android.com/google/play/billing/test

https://support.google.com/googleplay/android-developer/answer/6062777

Have a look through these links. Tbh just follow my documentation and you'll be good to go since I use this library in my projects as well. You can always create a testing track of your own in case you want to double check.
