### ISSUE TITLE
Subscription transaction details

### ISSUE THREAD

**Issue by broscr** [akshaaatt/Google-IAP#35]
Hi..
Will a method be added that returns purchase information as a result of the purchase?
Example... SubsId,purchaseToken and another sku details..

**Comment by akshaaatt** [comment]
I was just working on this 2 days back. The only setback on doing this is that you will have to add the GooglePlayBilling library as well again to be able to receive those objects. Right now all you need is to add my libraries' dependency but on doing this feature you'll have to add my library+GoogleBillingLibrary again.

Let me know if it's a really important use case because I didn't find the use case relevant for me hence discarded this addition.

**Comment by broscr** [comment]
I send the value returned from the purchase to the server, so it is actually necessary. I send and check the purchase token to the server and identify it directly from the server.Actually all I need is a purchase token. But as you said you need google billing library.
I would be grateful if you add this.

**Comment by akshaaatt** [comment]
Great job @broscr ! You have convinced me to have a definite solution for this and hence I have added DataWrappers around them and now you can all the purchase info and well as the skuDetails!

Thanks for getting me to deal with this :)

@MRZ07 you can be happy as well now :)

**Comment by broscr** [comment]
thanks you are one :)
